## Torch Fundamentals

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import torch
warnings.filterwarnings("ignore")

### Reshaping, Stacking, Squeezing and Unsqueezing tensors

In [5]:
# Create a Tensor of 12 elements
x = torch.arange(1,13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
# Reshaping the Created Tensor

x_reshaped = x.reshape([1,1,12])
x_reshaped

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])

In [20]:
# Stacking Tensors

# torch.stack
x_stacked = torch.stack([x, x, x, x], dim = 0)
print(x_stacked)

# torch.hstack
x_hstack = torch.hstack([x, x])
print(x_hstack)

# torch.vstack
x_vstack = torch.vstack([x,x])
print(x_vstack)

# tensor.view
z = x.view(1,12)
z[0][0] = 5
print(x, z)

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  5,  2,  3,  4,  5,  6,
         7,  8,  9, 10, 11, 12])
tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]) tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])


In [33]:
## Squeezing Tensors - removes all single dimensions from tensor

print(x_reshaped.shape)

print(x_reshaped.squeeze())
print(x_reshaped.squeeze().shape)


## Unsqueezing Tensors - adds a single dimension to a target tensor
print(x.unsqueeze(dim = 0))

torch.Size([1, 1, 12])
tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])
tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])


In [42]:
## permute - rearranges the dimensions accordingly

x_new = torch.rand(size = (2,5,3))
print(x_new)

tensor([[[0.0452, 0.8059, 0.7000],
         [0.8232, 0.3928, 0.4507],
         [0.7083, 0.1190, 0.2863],
         [0.4116, 0.4829, 0.9086],
         [0.1086, 0.7079, 0.7240]],

        [[0.2044, 0.5852, 0.5102],
         [0.6825, 0.9966, 0.2524],
         [0.1767, 0.0143, 0.8074],
         [0.0363, 0.6428, 0.3380],
         [0.4343, 0.6762, 0.8972]]])


## Indexing

Similar to indexing in NumPy

In [3]:
# Create tensor using arange
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
x[0].reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [7]:
x[0,2,2]

tensor(9)

## PyTorch default tensor datatype is float32
Convert PyTorch tensor to NumPy using `torch.tensor.numpy()`  
Convert NumPy ndarray to PyTorch tensor using `torch.from_numpy(ndarray)`

In [32]:
import torch
import numpy as np

# Create a NumPy array
n = np.arange(1.0,11.0)

# Convert NumPy to Torch Tensor
n_t = torch.from_numpy(n)

# Create a default torch tensor
t = torch.arange(1.0,11.0)

# Checking the datatypes
n_t.dtype, n.dtype, t.dtype

# View
tensor = n_t.view(1,10)
print(n_t)
tensor[0] += 100
print(n_t)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)
tensor([101., 102., 103., 104., 105., 106., 107., 108., 109., 110.],
       dtype=torch.float64)


In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch

In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [11]:
tensor_cpu = torch.tensor([1,2,3])
tensor_cpu

tensor([1, 2, 3])

In [12]:
tensor_gpu = tensor_cpu.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

### Working with GPU is not possible in case of NumPy

In [14]:
tensor_gpu_numpy = tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [21]:
tensor_cpu_numpy = tensor_gpu.cpu().numpy()
tensor_cpu_numpy

array([1, 2, 3], dtype=int64)