## Torch Fundamentals

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import torch
warnings.filterwarnings("ignore")

### Reshaping, Stacking, Squeezing and Unsqueezing tensors

In [5]:
# Create a Tensor of 12 elements
x = torch.arange(1,13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
# Reshaping the Created Tensor

x_reshaped = x.reshape([1,1,12])
x_reshaped

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])

In [20]:
# Stacking Tensors

# torch.stack
x_stacked = torch.stack([x, x, x, x], dim = 0)
print(x_stacked)

# torch.hstack
x_hstack = torch.hstack([x, x])
print(x_hstack)

# torch.vstack
x_vstack = torch.vstack([x,x])
print(x_vstack)

# tensor.view
z = x.view(1,12)
z[0][0] = 5
print(x, z)

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  5,  2,  3,  4,  5,  6,
         7,  8,  9, 10, 11, 12])
tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]) tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])


In [33]:
## Squeezing Tensors - removes all single dimensions from tensor

print(x_reshaped.shape)

print(x_reshaped.squeeze())
print(x_reshaped.squeeze().shape)


## Unsqueezing Tensors - adds a single dimension to a target tensor
print(x.unsqueeze(dim = 0))

torch.Size([1, 1, 12])
tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])
tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])


In [42]:
## permute - rearranges the dimensions accordingly

x_new = torch.rand(size = (2,5,3))
print(x_new)

tensor([[[0.0452, 0.8059, 0.7000],
         [0.8232, 0.3928, 0.4507],
         [0.7083, 0.1190, 0.2863],
         [0.4116, 0.4829, 0.9086],
         [0.1086, 0.7079, 0.7240]],

        [[0.2044, 0.5852, 0.5102],
         [0.6825, 0.9966, 0.2524],
         [0.1767, 0.0143, 0.8074],
         [0.0363, 0.6428, 0.3380],
         [0.4343, 0.6762, 0.8972]]])


## Indexing

Similar to indexing in NumPy

In [49]:
# Create tensor using arange

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [55]:
x[0].reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])