## Torch Fundamentals

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import torch
warnings.filterwarnings("ignore")

### Reshaping, Stacking, Squeezing and Unsqueezing tensors

In [5]:
# Create a Tensor of 12 elements
x = torch.arange(1,13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
# Reshaping the Created Tensor

x_reshaped = x.reshape([1,1,12])
x_reshaped

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])

In [20]:
# Stacking Tensors

# torch.stack
x_stacked = torch.stack([x, x, x, x], dim = 0)
print(x_stacked)

# torch.hstack
x_hstack = torch.hstack([x, x])
print(x_hstack)

# torch.vstack
x_vstack = torch.vstack([x,x])
print(x_vstack)

# tensor.view
z = x.view(1,12)
z[0][0] = 5
print(x, z)

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  5,  2,  3,  4,  5,  6,
         7,  8,  9, 10, 11, 12])
tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]) tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])


In [33]:
## Squeezing Tensors - removes all single dimensions from tensor

print(x_reshaped.shape)

print(x_reshaped.squeeze())
print(x_reshaped.squeeze().shape)


## Unsqueezing Tensors - adds a single dimension to a target tensor
print(x.unsqueeze(dim = 0))

torch.Size([1, 1, 12])
tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])
tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])


In [41]:
## permute - rearranges the dimensions accordingly

x_new = torch.rand(size = (2,5,3))
print(x_new)


tensor([[[0.0317, 0.1495, 0.9969],
         [0.0352, 0.5980, 0.8147],
         [0.2197, 0.6039, 0.4595],
         [0.4587, 0.0376, 0.5814],
         [0.2109, 0.7461, 0.0497]],

        [[0.2633, 0.9105, 0.2261],
         [0.7602, 0.3302, 0.4852],
         [0.4617, 0.6734, 0.6381],
         [0.8757, 0.8071, 0.9728],
         [0.4050, 0.0209, 0.9152]]])


RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 1 is not equal to len(dims) = 2